apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }} # has to match .spec.template.metadata.labels
  serviceName: {{ .Values.serviceName }}
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: {{ .Values.appName }} # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}
        args:
          - {{ .Values.image.args }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        volumeMounts:
        - name: www
          mountPath: {{ .Values.volumeMounts.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi



    