apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- ns.yaml
- redis.yaml
- payment.yaml

secretGenerator:
  - name: redis-config
    namespace: sns
    files:
      - secrets/redis.conf
      - secrets/redis_password

